spring.data.mongodb.uri=mongodb+srv://cryptobit_db_user:Fw9pvtuKuNgZh4kg@cluster0.hxxsi0p.mongodb.net/CryptoBit?appName=Cluster0
spring.data.mongodb.database=CryptoBit

# RED sepolia (Para test)
blockchain.node.url=https://eth-sepolia.g.alchemy.com/v2/1Pkc2TTICcS3m5T2SJsLF
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Red mainnet (Red real)
//blockchain.node.url=https://eth-mainnet.g.alchemy.com/v2/1Pkc2TTICcS3m5T2SJsLF
//logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG